# qenerate: plugin=pydantic_v1

query Emails {
  emails: app_interface_emails_v1 {
    name
    subject
    to {
      aliases
      services {
        ...EmailServiceOwners
      }
      clusters {
        name
      }
      namespaces {
        name
      }
      aws_accounts {
        accountOwners {
          email
        }
      }
      roles {
        users {
          ...EmailUser
        }
      }
      users {
        ...EmailUser
      }
    }
    body
  }
}
