# qenerate: plugin=pydantic_v2

query LdapGroupsRolesQuery {
  roles: roles_v1 {
    name
    ldapGroup {
      name
      notes
      membersAreOwners
    }
    users {
      org_username
    }
    user_policies {
      account {
        ...AWSAccountSSO
      }
    }
    aws_groups {
      account {
        ...AWSAccountSSO
      }
    }
  }
}
