# qenerate: plugin=pydantic_v2

query LdapGroupsAppInterfaceSettings {
  settings: app_interface_settings_v1 {
    ldapGroups {
      contactList
      credentials {
        ...VaultSecret
      }
    }
  }
}
