# qenerate: plugin=pydantic_v1

query OcmSubscriptionLabel {
  clusters: clusters_v1 {
    name
    spec {
      id
    }
    ocm {
      environment {
        ...OCMEnvironment
      }
      orgId

    }
    disable {
      integrations
    }
    ocmSubscriptionLabels
  }
}
