# qenerate: plugin=pydantic_v1

query OpenshiftGroupsManagedRoles {
  roles: roles_v1 {
    name
    users {
      ... User
    }
    expirationDate
    access {
      cluster {
        name
        auth {
          service
        }
      }
      group
    }
  }
}
