# qenerate: plugin=pydantic_v1

query CostNamespaces($filter: JSON) {
  namespaces: namespaces_v1(filter: $filter) {
    name
    app {
      name
    }
    cluster {
      name
      spec {
        external_id
      }
    }
  }
}
