"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


DEFINITION = """
query VPCResourcesAWSAccounts($filter: JSON) {
  accounts: awsaccounts_v1(filter: $filter) {
    name
    automationToken {
      path
      field
      format
      version
    }
    providerVersion
    resourcesDefaultRegion
    supportedDeploymentRegions
    terraformState {
      integrations {
        key
        integration
      }
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class VaultSecretV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")
    field: str = Field(..., alias="field")
    q_format: Optional[str] = Field(..., alias="format")
    version: Optional[int] = Field(..., alias="version")


class AWSTerraformStateIntegrationsV1(ConfiguredBaseModel):
    key: str = Field(..., alias="key")
    integration: str = Field(..., alias="integration")


class TerraformStateAWSV1(ConfiguredBaseModel):
    integrations: list[AWSTerraformStateIntegrationsV1] = Field(..., alias="integrations")


class AWSAccountV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    automation_token: VaultSecretV1 = Field(..., alias="automationToken")
    provider_version: str = Field(..., alias="providerVersion")
    resources_default_region: str = Field(..., alias="resourcesDefaultRegion")
    supported_deployment_regions: Optional[list[str]] = Field(..., alias="supportedDeploymentRegions")
    terraform_state: Optional[TerraformStateAWSV1] = Field(..., alias="terraformState")


class VPCResourcesAWSAccountsQueryData(ConfiguredBaseModel):
    accounts: Optional[list[AWSAccountV1]] = Field(..., alias="accounts")


def query(query_func: Callable, **kwargs: Any) -> VPCResourcesAWSAccountsQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        VPCResourcesAWSAccountsQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return VPCResourcesAWSAccountsQueryData(**raw_data)
