
[allowlist]
description = "Global Allowlist"

# Ignore based on any subset of the file path
paths = [
    '''reconcile\/test\/fixtures\/glitchtip\/api\/0\/projects\/nasa\/apollo-11-flight-control\/keys\/get.json$''',
]
