services:
  # Cache/Broker (Redis or Valkey compatible)
  cache:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - cache_data:/data
    networks:
      - qontract-development

volumes:
  cache_data:

networks:
  qontract-development:
    external: true
    name: qontract-development
