# qenerate: plugin=pydantic_v1

query MembershipSourceRolesQuery($filter: JSON) {
  roles: roles_v1(filter: $filter) {
    name
    labels
    path
    users {
      name
      org_username
      github_username
      quay_username
      slack_username
      pagerduty_username
      aws_username
      cloudflare_user
      public_gpg_key
      tag_on_cluster_updates
      tag_on_merge_requests
    }
    bots {
      name
      description
      org_username
      github_username
      gitlab_username
      openshift_serviceaccount
      quay_username
    }
  }
}
