# qenerate: plugin=pydantic_v1

query TerraformCloudflareAccounts {
  accounts: cloudflare_accounts_v1 {
    name
    providerVersion
    apiCredentials {
      ... VaultSecret
    }
    terraformStateAccount {
      name
      automationToken {
        ... VaultSecret
      }
      terraformState {
        provider
        bucket
        region
        integrations {
          integration
          key
        }
      }
    }
    deletionApprovals {
      expiration
      name
      type
    }
    enforceTwofactor
    type
  }
}
