# qenerate: plugin=pydantic_v1

query SkupperNetworks {
  skupper_networks: skupper_network_v1 {
    identifier
    siteControllerTemplates {
      ...SkupperSiteControllerTemplate
    }
    namespaces {
      name
      delete
      skupperSite {
        delete
        siteControllerTemplates {
          ...SkupperSiteControllerTemplate
        }
      }
      clusterAdmin
      cluster {
        name
        serverUrl
        insecureSkipTLSVerify
        jumpHost {
          ...CommonJumphostFields
        }
        spec {
          private
        }
        automationToken {
          ...VaultSecret
        }
        clusterAdminAutomationToken {
          ...VaultSecret
        }
        internal
        disable {
          integrations
        }
        peering {
          connections {
            provider
            ... on ClusterPeeringConnectionClusterRequester_v1 {
              cluster {
                name
              }
            }
            ... on ClusterPeeringConnectionClusterAccepter_v1 {
              cluster {
                name
              }
            }
          }
        }
      }
    }
  }
}
