# qenerate: plugin=pydantic_v1

fragment OpenshiftServiceAccountToken on ServiceAccountTokenSpec_v1 {
    name
    namespace {
        name
        cluster {
            ... OcConnectionCluster
        }
    }
    serviceAccountName
}
