# qenerate: plugin=pydantic_v1

query ServiceAccountTokens {
  namespaces: namespaces_v1 {
    name
    delete
    clusterAdmin
    cluster {
      ... OcConnectionCluster
    }
    sharedResources {
      openshiftServiceAccountTokens {
        ... OpenshiftServiceAccountToken
      }
    }
    openshiftServiceAccountTokens {
      ... OpenshiftServiceAccountToken
    }
  }
}
