{
 "title": "Terraform Repo",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pipelinerun",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"terraform-repo-production\", pod=~\"tf-repo.+\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Terraform Repo Inventory by AWS Account",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qontract_reconcile_terraform_repo_inventory",
     "legendFormat": "{{aws_account}}"
    }
   ]
  },
  {
   "title": "How to use",
   "type": "text",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "options": {
    "content": "1. Find the name of your `PipelineRun` in [Slack](https://redhat.enterprise.slack.com/archives/C07F3A80H51)\n2. Select the matching name in the `pipelinerun` variable dropdown.\n3. Logs for that PLR will be displayed."
   }
  },
  {
   "title": "PipelineRun Logs",
   "type": "logs",
   "gridPos": { "h": 26, "w": 13, "x": 11, "y": 4 },
   "targets": [
    {
     "expression": "fields @timestamp, message, kubernetes.labels.tekton_dev_pipelineRun |\nfilter kubernetes.container_name not like /place-scripts|prepare|working-dir-initializer/ |\nfilter kubernetes.labels.tekton_dev_pipelineRun like /$pipelinerun/ |\nfilter message not like \"using gql endpoint\" |\nsort @timestamp asc",
     "logGroups": [
      {
       "accountId": "744086762512",
       "arn": "arn:aws:logs:us-east-1:744086762512:log-group:appsrep09ue1.terraform-repo-production:*",
       "name": "appsrep09ue1.terraform-repo-production"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PipelineRun Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_pipelinerun_duration_seconds{namespace=~\"terraform-repo.+\", pipeline=\"tf-repo-push-deploy-pipeline\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"terraform apply\" Durations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds{namespace=~\"terraform-repo.+\", task=\"run-terraform-operation\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}