{
 "title": "External Resource Logs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "provision_provider",
    "query": {
     "query": "label_values(external_resources_resource_status,provision_provider)"
    }
   },
   {
    "name": "provisioner",
    "query": {
     "query": "label_values(external_resources_resource_status{provision_provider=\"$provision_provider\"},provisioner_name)"
    }
   },
   {
    "name": "provider",
    "query": {
     "query": "label_values(external_resources_resource_status{provision_provider=\"$provision_provider\", provisioner_name=\"$provisioner\"},provider)"
    }
   },
   {
    "name": "identifier",
    "query": {
     "query": "label_values(external_resources_resource_status{provision_provider=\"$provision_provider\", provisioner_name=\"$provisioner\", provider=\"$provider\"},identifier)"
    }
   },
   {
    "name": "jobname",
    "label": "jobname",
    "query": {
     "query": "label_values(external_resources_resource_status{provision_provider=\"$provision_provider\", provisioner_name=\"$provisioner\", provider=\"$provider\", identifier=\"$identifier\"},job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# ${provision_provider}/${provisioner}/${provider}/${identifier}\n\n"
   },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Reconcile Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(external_resources_reconcile_errors{provision_provider=\"$provision_provider\", provisioner_name=\"$provisioner\", provider=\"$provider\", identifier=\"$identifier\"}) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile Time (seconds)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(external_resources_reconcile_time{provision_provider=\"$provision_provider\", provisioner_name=\"$provisioner\", provider=\"$provider\", identifier=\"$identifier\"}) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "dimensions": {
      "LogGroupName": "appsrep09ue1.external-resources-jobs"
     },
     "expression": "filter kubernetes.pod_name like /$jobname/ | stats count(@timestamp) as logs by bin(30s)",
     "logGroups": [
      {
       "accountId": "744086762512",
       "arn": "arn:aws:logs:us-east-1:744086762512:log-group:appsrep09ue1.external-resources-jobs:*",
       "name": "appsrep09ue1.external-resources-jobs"
      }
     ],
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "metricQueryType": 1,
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/Logs", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "IncomingLogEvents", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "appsrep09ue1.external-resources-jobs"
         },
         "property": { "name": "LogGroupName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(IncomingLogEvents) FROM \"AWS/Logs\" WHERE LogGroupName = 'appsrep09ue1.external-resources-jobs' AND FilterName",
     "statistic": "Sum",
     "statsGroups": [ "bin(30s)" ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expression": "fields @timestamp, message | filter kubernetes.pod_name like /$jobname/ ",
     "logGroups": [
      {
       "accountId": "744086762512",
       "arn": "arn:aws:logs:us-east-1:744086762512:log-group:appsrep09ue1.external-resources-jobs:*",
       "name": "appsrep09ue1.external-resources-jobs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}