{
 "title": "Integrations",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Slowest integrations (shard average)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, avg(qontract_reconcile_last_run_seconds) by (integration))"
    }
   ]
  },
  {
   "title": "Errors in the last 10m",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(qontract_reconcile_last_run_status[10m])) by (integration, shard_id) > 0"
    }
   ]
  },
  {
   "title": "Openshift reconciliation time SLO (30d)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{le=\"1200.0\",name=~\"reconcile\\\\.utils\\\\.oc\\\\.OC[^.]*\\\\.(apply|replace|delete|create)\",integration!~\"terraform-resources|sql-query\"}[30d])) / sum(rate(qontract_reconcile_function_elapsed_seconds_since_bundle_commit_count{name=~\"reconcile\\\\.utils\\\\.oc\\\\.OC[^.]*\\\\.(apply|replace|delete|create)\",integration!~\"terraform-resources|sql-query\"}[30d]))"
    }
   ]
  },
  {
   "title": "Integrations p50 reconcile time openshift resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (integration, le) (qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{name=~\"reconcile\\\\.utils\\\\.oc\\\\.OC[^.]*\\\\.(apply|replace|delete)\",integration!~\"terraform-resources|sql-query\"}))",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Integrations p90 reconcile time openshift resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (integration, le) (qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{name=~\"reconcile\\\\.utils\\\\.oc\\\\.OC[^.]*\\\\.(apply|replace|delete)\",integration!~\"terraform-resources|sql-query\"}))",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Integrations p99 reconcile time openshift resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (integration, le) (qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{name=~\"reconcile\\\\.utils\\\\.oc\\\\.OC[^.]*\\\\.(apply|replace|delete)\",integration!~\"terraform-resources|sql-query\"}))",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Integration run-time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(qontract_reconcile_last_run_seconds) by (integration, shard_id)"
    }
   ]
  },
  {
   "title": "Integration Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum(qontract_reconcile_last_run_status) by (integration, shard_id) > 0"
    }
   ]
  },
  {
   "title": "Integration extended early exit cache HIT percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(qontract_reconcile_extended_early_exit_total{cache_status=\"HIT\"}[1h])) by (integration, shard) / sum(rate(qontract_reconcile_extended_early_exit_total[1h])) by (integration, shard)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Integration Likely Reconcile Loops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum(qontract_reconcile_extended_early_exit_applied_count{cache_status=\"EXPIRED\"}) by (integration, shard) > 0"
    }
   ]
  }
 ]
}