{
 "title": "SAPM Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Parallel Open MRs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sapm_parallel_open_mrs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MR Opened By Batch Size",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(sapm_opened_mrs_total[5m])) by (batch_size))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MR Closed By Reason",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum by (reason) (increase(sapm_closed_mrs_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of un-batchable MRs Opened",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(sapm_opened_mrs_total{is_batchable=\"False\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}