{
 "title": "RedHat SSO IDP Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SSO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of managed clusters by integration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max by (org_id, ocm_environment) (rhidp_managed_clusters{integration=~\"rhidp-sso-client.*\"}))",
     "legendFormat": "rhidp-sso-client integration"
    },
    {
     "expr": "sum(max by (org_id, ocm_environment) (rhidp_managed_clusters{integration=~\"ocm-oidc-idp.*\"}))",
     "legendFormat": "ocm-oidc-idp integration"
    }
   ]
  },
  {
   "title": "Managed SSO Clients by the rhidp-sso-client integration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max by (ocm_environment) (rhidp_sso_client_number_of_clients{integration=~\"rhidp-sso-client.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAT Expiration Date (keycloak prod)",
   "type": "stat",
   "description": "Expiration date for prod initial-access-token (IAT)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(rhidp_sso_client_inital_access_token_expiration{integration=\"rhidp-sso-client\", path=\"apps/sso-iat/share-with/app/ai-app-sre/iat\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAT Expiration Date (keycloak stage)",
   "type": "stat",
   "description": "Expiration date for stage initial-access-token (IAT)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(rhidp_sso_client_inital_access_token_expiration{integration=\"rhidp-sso-client\", path=\"apps/sso-iat/share-with/app/ai-app-sre/iat-stage\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}