{
 "title": "AUS Cluster Upgrade Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_id",
    "label": "OCM Organization",
    "query": {
     "query": "aus_cluster_upgrade_policy_info"
    }
   },
   {
    "name": "sectors",
    "label": "Sectors",
    "query": {
     "query": "label_values(aus_cluster_upgrade_policy_info{org_id=~\"$org_id\"},sector)"
    }
   },
   {
    "name": "workloads",
    "label": "Workloads",
    "query": {
     "query": "label_values(aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\"},workloads)"
    }
   },
   {
    "name": "clusters",
    "label": "Clusters",
    "query": {
     "query": "label_values(aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*${workloads}.*\"},cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operational Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"}) by (current_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Soaking Versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "label_join((aus_cluster_version_remaining_soak_days >= 0) * on (cluster_uuid, soaking_version) (clamp_max(changes(min(aus_cluster_version_remaining_soak_days) by(cluster_uuid, soaking_version)[1h:1m]), 1) > 0) * on (cluster_uuid) group_left(cluster_name, current_version, workloads, schedule, sector, soak_days) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"}, \"cluster_soaking_version\", \"-\", \"cluster_uuid\", \"soaking_version\")",
     "legendFormat": "{{cluster_name}} - {{org_id}}"
    },
    {
     "expr": "label_join(delta(min((aus_cluster_version_remaining_soak_days >= 0)) by(cluster_uuid, soaking_version)[1h:1m]) * -24 * on (cluster_uuid) group_left aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} > 0, \"cluster_soaking_version\", \"-\", \"cluster_uuid\", \"soaking_version\") > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining soak days per cluster and version",
   "type": "table",
   "description": "A numeric value represents the remaining soak days per version and cluster<br/>\nA 🎉 is displayed for versions which have soaked enough and are ready to be upgraded to <br/>\nA ⏰ is displayed for versions scheduled to be upgraded to <br/>\nA 💫 is displayed for versions which are being upgraded to <br/>\nUpgrades taking more than 6 hours will be highlighted with ❗️<br/>\nUpgrade paths to blocked versions are displayed with ⛔<br/>",
   "gridPos": { "h": 21, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "aus_cluster_version_remaining_soak_days * on (cluster_uuid) group_left(cluster_name, workloads, schedule, sector, cluster_name_version) label_join(aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"}, \"cluster_name_version\", \" @ \", \"cluster_name\", \"current_version\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters w/ failed upgrades 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(\n    resets(\n    ((aus_cluster_version_remaining_soak_days == 0 or aus_cluster_version_remaining_soak_days == -2)*-1)[24h:]\n    )\n) by (cluster_uuid, soaking_version)\n* on (cluster_uuid, soaking_version) count(aus_cluster_version_remaining_soak_days) by (cluster_uuid, soaking_version)\n* on (cluster_uuid) group_left(cluster_name, ocm_env, org_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed upgrades 24h",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n    resets(\n    ((aus_cluster_version_remaining_soak_days == 0 or aus_cluster_version_remaining_soak_days == -2)*-1)[24h:]\n    )\n) by (cluster_uuid, soaking_version)\n* on (cluster_uuid, soaking_version) count(aus_cluster_version_remaining_soak_days) by (cluster_uuid, soaking_version)\n* on (cluster_uuid) group_left(cluster_name, ocm_env, org_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters upgrades 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(sum by(cluster_uuid, current_version)(last_over_time({__name__=\"aus_cluster_upgrade_policy_info\"}[25h]))) by (__name__, cluster_uuid) * on (cluster_uuid) group_left (org_id, org_name, cluster_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} > 1) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters upgrades 24h",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "count(sum by(cluster_uuid, current_version)(last_over_time({__name__=\"aus_cluster_upgrade_policy_info\"}[25h]))) by (__name__, cluster_uuid) * on (cluster_uuid) group_left (org_id, org_name, cluster_name, current_version) aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"} * on (cluster_uuid) group_left(previous_version) label_replace(aus_cluster_upgrade_policy_info offset 25h, \"previous_version\", \"$1\", \"current_version\", \"(.+)\") > 1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Cluster Upgrade Policies",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "aus_cluster_upgrade_policy_info{org_id=~\"$org_id\", sector=~\"$sectors\", workloads=~\".*$workloads.*\", cluster_name=~\"$clusters\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}