{
 "title": "AUS Addon Upgrade Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "org_id", "label": "OCM Organization", "query": { "query": "aus_addon_upgrade_policy_info" } },
   {
    "name": "workloads",
    "label": "Workloads",
    "query": {
     "query": "label_values(aus_addon_upgrade_policy_info, workloads)"
    }
   },
   {
    "name": "addon",
    "label": "Addons",
    "query": {
     "query": "label_values(aus_addon_upgrade_policy_info, addon)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${addon}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "addon" },
  {
   "title": "Addon Version Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aus_addon_upgrade_policy_info{workloads=~\".*$workloads.*\", org_id=~\".*$org_id.*\", addon=\"$addon\"}) by (current_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Soaking Addon Versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "label_join((aus_addon_version_remaining_soak_days{addon=\"$addon\"} >= 0) * on (cluster_uuid, soaking_version) (clamp_max(changes(min(aus_addon_version_remaining_soak_days{addon=\"$addon\"}) by(cluster_uuid, soaking_version)[1h:1m]), 1) > 0) * on (cluster_uuid) group_left(cluster_name, current_version, workloads, schedule, sector, soak_days) aus_cluster_upgrade_policy_info{workloads=~\".*$workloads.*\", org_id=~\".*$org_id.*\", addon=\"$addon\"}, \"cluster_soaking_version\", \"-\", \"cluster_uuid\", \"soaking_version\")",
     "legendFormat": "{{cluster_name}} - {{org_id}}"
    },
    {
     "expr": "label_join(delta(min((aus_addon_version_remaining_soak_days{addon=\"$addon\"} >= 0)) by(cluster_uuid, soaking_version)[1h:1m]) * -24 * on (cluster_uuid) group_left aus_addon_upgrade_policy_info{workloads=~\".*$workloads.*\", org_id=~\".*$org_id.*\", addon=\"$addon\"} > 0, \"cluster_soaking_version\", \"-\", \"cluster_uuid\", \"soaking_version\") > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining soak days per cluster and addon version",
   "type": "table",
   "description": "A numeric value represents the remaining soak days per version and cluster<br/>\nA 🎉 is displayed for versions which have soaked enough and are ready to be upgraded to <br/>\nA ⏰ is displayed for versions scheduled to be upgraded to <br/>\nA 💫 is displayed for versions which are being upgraded to <br/>\nUpgrades taking more than 6 hours will be highlighted with ❗️<br/>\nUpgrade paths to blocked versions are displayed with ⛔<br/>",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "aus_addon_version_remaining_soak_days{addon=\"$addon\"} * on (cluster_uuid) group_left(cluster_name, workloads, schedule, sector, cluster_name_version) label_join(aus_addon_upgrade_policy_info{workloads=~\".*$workloads.*\", org_id=~\".*$org_id.*\", addon=\"$addon\"}, \"cluster_name_version\", \" @ \", \"cluster_name\", \"current_version\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Addon upgrades 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(sum by(cluster_uuid, addon, current_version)(last_over_time({__name__=\"aus_addon_upgrade_policy_info\"}[25h]))) by (__name__, cluster_uuid, addon) * on (cluster_uuid, addon) group_left (org_id, org_name, cluster_name, current_version) aus_addon_upgrade_policy_info{workloads=~\".*$workloads.*\", org_id=~\".*$org_id.*\", addon=\"$addon\"} > 1) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Addon upgrades 24h",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "count(sum by(cluster_uuid, current_version)(last_over_time({__name__=\"aus_addon_upgrade_policy_info\"}[25h]))) by (__name__, cluster_uuid, addon) * on (cluster_uuid, addon) group_left (org_id, org_name, cluster_name, current_version) aus_addon_upgrade_policy_info{workloads=~\".*$workloads.*\", org_id=~\".*$org_id.*\"} * on (cluster_uuid, addon) group_left(previous_version) label_replace(aus_addon_upgrade_policy_info offset 25h, \"previous_version\", \"$1\", \"current_version\", \"(.+)\") > 1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}