# qenerate: plugin=pydantic_v2

fragment VpcPeeringsValidatorPeeredCluster on Cluster_v1 {
  name
  allowedToBypassPublicPeeringRestriction
  network {
    vpc
  }
  spec {
    private
  }
  internal
}
