# qenerate: plugin=pydantic_v1

query VpcPeeringsValidator {
  clusters: clusters_v1 {
    name
    network {
      vpc
    }
    spec {
      private
    }
    internal
    peering {
      connections {
        provider
        ... on ClusterPeeringConnectionAccount_v1 {
          vpc {
            cidr_block
            name
          }
        }
        ... on ClusterPeeringConnectionAccountVPCMesh_v1{
          name
          account {
            name
          }
          tags
        }
        ... on ClusterPeeringConnectionClusterRequester_v1 {
          cluster {
            ... VpcPeeringsValidatorPeeredCluster
            network {
              vpc
            }
          }
        }
        ... on ClusterPeeringConnectionClusterAccepter_v1 {
          cluster {
            ... VpcPeeringsValidatorPeeredCluster
            network {
              vpc
            }
          }
        }
      }
    }
  }
}
