# qenerate: plugin=pydantic_v1

query SLODocuments {
  slo_documents: slo_document_v1 {
    path
    name
    namespaces {
      prometheusAccess {
         url
      }
      namespace {
        path
        name
        app {
          name
        }
        environment {
          name
          product {
            name
          }
        }
        cluster {
          name
          automationToken {
          ... VaultSecret
          }
          prometheusUrl
          spec {
            private
          }
        }
      }
    }
    slos {
      name
      expr
      SLIType
      SLISpecification
      SLOParameters {
        window
      }
      SLOTarget
      SLOTargetUnit
      SLODetails
      prometheusRules
    }
  }
}
