# qenerate: plugin=pydantic_v1

query SLODocuments {
  slo_documents: slo_document_v1 {
    name
    namespaces {
      prometheusAccess {
         url
         username {
         ... VaultSecret
         }
         password {
           ... VaultSecret
         }
      }
      namespace {
        name
        app {
          name
        }
        cluster {
          name
          automationToken {
          ... VaultSecret
          }
          prometheusUrl
          spec {
            private
          }
        }
      }
    }
    slos {
      name
      expr
      SLIType
      SLOParameters {
        window
      }
      SLOTarget
      SLOTargetUnit
    }
  }
}
