# qenerate: plugin=pydantic_v1

query Projects {
  glitchtip_projects: glitchtip_projects_v1 {
    name
    platform
    teams {
      name
      roles {
        glitchtip_roles {
          organization {
            name
          }
          role
        }
        users {
          name
          org_username
        }
      }
    }
    organization {
      name
      instance {
        name
      }
    }
    # for glitchtip-project-dsn
    namespaces {
      name
      delete
      clusterAdmin
      cluster {
        name
        serverUrl
        insecureSkipTLSVerify
        jumpHost {
          ...CommonJumphostFields
        }
        spec {
          private
        }
        automationToken {
          ...VaultSecret
        }
        clusterAdminAutomationToken {
          ...VaultSecret
        }
        internal
        disable {
          integrations
        }
      }
    }
    # for gltichtip access revalidation
    app {
      path
    }
  }
}
