# qenerate: plugin=pydantic_v1

query CloudflareDnsZone {
  zones: cloudflare_dns_zone_v1 {
    identifier
    zone
    account {
      name
      type
      description
      providerVersion
      enforceTwofactor
      apiCredentials {
        ... VaultSecret
      }
      terraformStateAccount {
        name
        consoleUrl
        terraformUsername
        automationToken {
          ... VaultSecret
        }
        terraformState {
          provider
          bucket
          region
          integrations {
            integration
            key
          }
        }
      }
      deletionApprovals {
        expiration
        name
        type
      }
    }
    records {
      identifier
      name
      type
      ttl
      value
      priority
      data {
        algorithm
        protocol
        public_key
        digest_type
        digest
        key_tag
        flags
      }
    }
    type
    plan
    delete
  }
}
