"""
Generated by qenerate plugin=pydantic_v2. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    ConfigDict,
    Field,
    Json,
)


DEFINITION = """
query QuayReposApiApps {
  apps: apps_v1 {
    quayRepos {
      org {
        name
        instance {
          name
        }
      }
      items {
        name
        public
        description
      }
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid'
    )


class QuayInstanceV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")


class QuayOrgV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    instance: QuayInstanceV1 = Field(..., alias="instance")


class AppQuayReposItemsV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    public: bool = Field(..., alias="public")
    description: str = Field(..., alias="description")


class AppQuayReposV1(ConfiguredBaseModel):
    org: QuayOrgV1 = Field(..., alias="org")
    items: list[AppQuayReposItemsV1] = Field(..., alias="items")


class AppV1(ConfiguredBaseModel):
    quay_repos: Optional[list[AppQuayReposV1]] = Field(..., alias="quayRepos")


class QuayReposApiAppsQueryData(ConfiguredBaseModel):
    apps: Optional[list[AppV1]] = Field(..., alias="apps")


def query(query_func: Callable, **kwargs: Any) -> QuayReposApiAppsQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        QuayReposApiAppsQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return QuayReposApiAppsQueryData(**raw_data)
