# qenerate: plugin=pydantic_v1

query RhcsCerts {
  namespaces: namespaces_v1 {
    name
    delete
    clusterAdmin
    openshiftResources {
      provider
      ... on NamespaceOpenshiftResourceRhcsCert_v1 {
        secret_name
        service_account_name
        service_account_password {
          ... on VaultSecret_v1 {
            path
            field
            version
          }
        }
        auto_renew_threshold_days
        annotations
      }
    }
    sharedResources {
      openshiftResources {
        provider
        ... on NamespaceOpenshiftResourceRhcsCert_v1 {
          secret_name
          service_account_name
          service_account_password {
            ... on VaultSecret_v1 {
              path
              field
              version
            }
          }
          auto_renew_threshold_days
          annotations
        }
      }
    }
    cluster {
      name
      serverUrl
      insecureSkipTLSVerify
      jumpHost {
        ...CommonJumphostFields
      }
      automationToken {
        ...VaultSecret
      }
      clusterAdminAutomationToken {
        ...VaultSecret
      }
      internal
      disable {
        integrations
      }
    }
  }
}
