# qenerate: plugin=pydantic_v2

query RhcsCerts {
  namespaces: namespaces_v1 {
    name
    delete
    clusterAdmin
    openshiftResources {
      ...OpenshiftResourceRhcsCert
    }
    sharedResources {
      openshiftResources {
        ...OpenshiftResourceRhcsCert
      }
    }
    cluster {
      name
      serverUrl
      insecureSkipTLSVerify
      automationToken {
        ...VaultSecret
      }
      automationTokens {
        name
        namespace
        active
        delete
        secret {
          ...VaultSecret
        }
      }
      clusterAdminAutomationToken {
        ...VaultSecret
      }
      clusterAdminAutomationTokens {
        name
        namespace
        active
        delete
        secret {
          ...VaultSecret
        }
      }
      internal
      disable {
        integrations
      }
    }
  }
}
