# qenerate: plugin=pydantic_v2

query Integrations {
  integrations: integrations_v1 {
    name
    upstream
    managed {
      namespace {
        path
        name
        environment {
          name
          parameters
        }
        cluster {
          name
          labels
          serverUrl
          insecureSkipTLSVerify
          jumpHost {
            ...CommonJumphostFields
          }
          automationToken {
            ...VaultSecret
          }
        }
      }
      spec {
        cache
        command
        disableUnleash
        environmentAware
        extraArgs
        extraEnv {
          secretName
          secretKey
          name
          value
        }
        internalCertificates
        logs {
          slack
          googleChat
          slackErrorFilter
        }
        resources {
          ...DeployResourcesFields
        }
        fluentdResources {
          ...DeployResourcesFields
        }
        sleepDurationSecs
        state
        storage
        storageClassName
        trigger
        cron
        dashdotdb
        concurrencyPolicy
        restartPolicy
        successfulJobHistoryLimit
        failedJobHistoryLimit
        imageRef
        enablePushgateway
      }
      sharding {
        strategy

        ... on StaticSharding_v1 {
          shards
        }

        ... on OpenshiftClusterSharding_v1 {
          shardSpecOverrides {
            shard {
              name
            }
            imageRef
            disabled
            resources {
              ...DeployResourcesFields
            }
            subSharding {
              strategy
              ... on StaticSubSharding_v1 {
                shards
              }
            }
          }
        }

        ... on OCMOrganizationSharding_v1 {
          shardSpecOverrides {
            shard {
              ...MinimalOCMOrganization
            }
            imageRef
            disabled
            resources {
              ...DeployResourcesFields
            }
          }
        }

        ... on AWSAccountSharding_v1 {
          shardSpecOverrides {
            shard {
              name
              disable {
                integrations
              }
            }
            imageRef
            disabled
            resources {
              ...DeployResourcesFields
            }
          }
        }
      }
    }
  }
}
