# qenerate: plugin=pydantic_v1

# TODO: longterm our codebase should be able to work with pydantic's Json type
# qenerate: map_gql_scalar=JSON -> str

query TerraformResourcesNamespaces {
  namespaces: namespaces_v1 {
    name
    delete
    clusterAdmin
    managedExternalResources
    externalResources {
      provider
      provisioner {
        name
      }
      ... on NamespaceTerraformProviderResourceAWS_v1 {
        resources {
            output_format {
            provider
            ... on NamespaceTerraformResourceGenericSecretOutputFormat_v1 {
                data
            }
            }
            provider
            ... on NamespaceTerraformResourceRDS_v1 {
                region
                identifier
                defaults
                availability_zone
                parameter_group
                old_parameter_group
                overrides
                output_resource_name
                enhanced_monitoring
                replica_source
                output_resource_db_name
                reset_password
                ca_cert {
                    ... VaultSecret
                }
                annotations
                event_notifications {
                    destination
                    source_type
                    event_categories
                }
            }
            ... on NamespaceTerraformResourceS3_v1 {
                region
                identifier
                defaults
                overrides
                sqs_identifier
                s3_events
                sns_event_notifications: event_notifications {
                    destination_type
                    destination
                    event_type
                    filter_prefix
                    filter_suffix
                }
                bucket_policy
                output_resource_name
                storage_class
                annotations
            }
            ... on NamespaceTerraformResourceElastiCache_v1 {
                identifier
                defaults
                parameter_group
                region
                overrides
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceServiceAccount_v1 {
                identifier
                variables
                policies
                user_policy
                output_resource_name
                annotations
                aws_infrastructure_access {
                    cluster {
                        name
                    }
                    access_level
                    assume_role
                }
            }
            ... on NamespaceTerraformResourceSecretsManagerServiceAccount_v1 {
                identifier
                secrets_prefix
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceRole_v1 {
                identifier
                assume_role {
                    AWS
                    Service
                }
                assume_condition
                inline_policy
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceSQS_v1 {
                region
                identifier
                output_resource_name
                annotations
                specs {
                    defaults
                    queues {
                        key
                        value
                    }
                }
            }
            ... on NamespaceTerraformResourceSNSTopic_v1 {
                defaults
                region
                identifier
                output_resource_name
                fifo_topic
                inline_policy
                annotations
                subscriptions
                {
                    protocol
                    endpoint
                }
            }
            ... on NamespaceTerraformResourceDynamoDB_v1 {
                region
                identifier
                output_resource_name
                annotations
                specs {
                    defaults
                    tables {
                        key
                        value
                    }
                }
            }
            ... on NamespaceTerraformResourceECR_v1 {
                identifier
                region
                output_resource_name
                public
                annotations
            }
            ... on NamespaceTerraformResourceS3CloudFront_v1 {
                region
                identifier
                defaults
                output_resource_name
                storage_class
                annotations
            }
            ... on NamespaceTerraformResourceS3SQS_v1 {
                region
                identifier
                defaults
                kms_encryption
                output_resource_name
                storage_class
                annotations
            }
            ... on NamespaceTerraformResourceCloudWatch_v1 {
                region
                identifier
                defaults
                es_identifier
                filter_pattern
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceKMS_v1 {
                region
                identifier
                defaults
                overrides
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceElasticSearch_v1 {
                region
                identifier
                defaults
                output_resource_name
                annotations
                publish_log_types
            }
            ... on NamespaceTerraformResourceACM_v1 {
                region
                identifier
                secret {
                    ... VaultSecret
                }
                domain {
                    domain_name
                    alternate_names
                }
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceKinesis_v1 {
                region
                identifier
                defaults
                es_identifier
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceS3CloudFrontPublicKey_v1 {
                region
                identifier
                secret {
                    ... VaultSecret
                }
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceALB_v1 {
                region
                identifier
                vpc {
                    vpc_id
                    cidr_block
                    subnets {
                        id
                    }
                }
                certificate_arn
                ingress_cidr_blocks
                idle_timeout
                enable_http2
                ip_address_type
                targets {
                    name
                    default
                    ips
                    openshift_service
                }
                rules {
                    condition {
                        type
                        ... on NamespaceTerraformResourceALBConditionHostHeader_v1 {
                            host_header
                        }
                        ... on NamespaceTerraformResourceALBConditionHTTPRequestMethod_v1 {
                            http_request_method
                        }
                        ... on NamespaceTerraformResourceALBConditionPathPattern_v1 {
                            path_pattern
                        }
                        ... on NamespaceTerraformResourceALBConditionSourceIP_v1 {
                            source_ip
                        }
                    }
                    action {
                        type
                        ... on NamespaceTerraformResourceALBActionForward_v1 {
                            forward {
                                target_group {
                                    target
                                    weight
                                }
                            }
                        }
                        ... on NamespaceTerraformResourceALBActionFixedResponse_v1 {
                            fixed_response {
                                content_type
                                message_body
                                status_code
                            }
                        }
                    }
                }
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceSecretsManager_v1 {
                region
                identifier
                secret {
                    ... VaultSecret
                }
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceASG_v1 {
                region
                identifier
                defaults
                cloudinit_configs {
                    filename
                    content_type
                    content
                }
                variables
                overrides
                extra_tags
                image {
                    provider
                    ... on ASGImageGit_v1 {
                    tag_name
                    url
                    ref
                    upstream {
                        instance {
                            name
                            token {
                                ... VaultSecret
                            }
                        }
                        name
                    }
                    }
                    ... on ASGImageStatic_v1 {
                        tag_name
                        value
                    }
                }
                output_resource_name
                annotations
            }
            ... on NamespaceTerraformResourceRoute53Zone_v1 {
                region
                identifier
                name
                output_resource_name
                annotations
                records {
                    name
                    type
                    ttl
                    alias {
                        name
                        zone_id
                        evaluate_target_health
                    }
                    weighted_routing_policy {
                        weight
                    }
                    geolocation_routing_policy {
                        continent
                        country
                        subdivision
                    }
                    set_identifier
                    records
                }
            }
            ... on NamespaceTerraformResourceRosaAuthenticator_V1 {
                region
                identifier
                api_proxy_uri
                cognito_callback_bucket_name
                certificate_arn
                domain_name
                network_interface_ids
                openshift_ingress_load_balancer_arn
                insights_callback_urls
                output_resource_name
                annotations
                vpc_id
                subnet_ids
                vpce_id
                defaults
            }
            ... on NamespaceTerraformResourceRosaAuthenticatorVPCE_V1 {
                region
                identifier
                subnet_ids,
                vpc_id,
                output_resource_name
                annotations
                defaults
            }
        }
      }
    }
    environment {
      name
    }
    app {
      name
    }
    cluster {
      name
      serverUrl
      insecureSkipTLSVerify
      jumpHost {
        ... CommonJumphostFields
      }
      automationToken {
        ... VaultSecret
      }
      clusterAdminAutomationToken {
        ... VaultSecret
      }
      spec {
        region
      }
      internal
      disable {
        integrations
      }
    }
  }
}
