# qenerate: plugin=pydantic_v1

query FleetLabelSpecs {
    fleet_labels_specs: fleet_labels_specs_v1 {
        name
        path
        managedSubscriptionLabelPrefix
        dryRunLabelSynchronization
        ocm {
            name
            environment {
                url
            }
            accessTokenClientId
            accessTokenClientSecret {
                ... VaultSecret
            }
            accessTokenUrl
        }
        labelDefaults {
            name
            matchSubscriptionLabels
            subscriptionLabelTemplate {
                path {
                    content
                }
                type
                variables
            }
        }
        clusters {
            name
            serverUrl
            subscriptionId
            clusterId
            subscriptionLabels
        }
    }
}
