# qenerate: plugin=pydantic_v1

query AWSAccountManagerAccounts {
  accounts: awsaccounts_v1 {
    ... AWSAccountManaged
    resourcesDefaultRegion
    automationToken {
      ...VaultSecret
    }
    disable {
      integrations
    }
    automationRole {
      awsAccountManager
    }
    # for the requests via "payer account"
    account_requests {
      path
      name
      description
      accountOwner {
        name
        email
      }
      organization {
        ou
        tags
        payerAccount {
          path
        }
      }
      quotaLimits {
        path
      }
      resourcesDefaultRegion
      supportedDeploymentRegions
      uid
      additionalFeatures
      accountFileTargetPath
    }
    organization_accounts {
      ... AWSAccountManaged
    }
    organizationAccountTags
  }
}
