# qenerate: plugin=pydantic_v2

query AWSAccountsCloudwatchLogRetentionCleanup {
  accounts: awsaccounts_v1 {
    name
    resourcesDefaultRegion
    automationToken {
      ...VaultSecret
    }
    disable {
      integrations
    }
    organization {
      ...AWSOrganization
    }
    cleanup {
      provider
      ... on AWSAccountCleanupOptionCloudWatch_v1 {
        regex
        retention_in_days
        delete_empty_log_group
        region
      }
    }
  }
}
