# qenerate: plugin=pydantic_v2

query Jumphosts($hostname: String) {
  jumphosts: jumphosts_v1(hostname: $hostname) {
    ...CommonJumphostFields
    clusters {
      name
      network {
        vpc
      }
    }
  }
}
