# qenerate: plugin=pydantic_v2

query Maintenances {
  maintenances: maintenance_v1 {
    name
    message
    scheduledStart
    scheduledEnd
    affectedServices {
      name
    }
    announcements {
      provider
      ... on MaintenanceStatuspageAnnouncement_v1 {
        page {
          name
        }
        remindSubscribers
        notifySubscribersOnStart
        notifySubscribersOnCompletion
      }
    }
  }
}
