# qenerate: plugin=pydantic_v2

query StatusPages {
  status_pages: status_page_v1 {
    name
    description
    pageId
    url
    apiUrl
    credentials {
      ...VaultSecret
    }
    components {
      name
      displayName
      description
      path
      groupName
      app {
        name
      }
      status_config: status {
        provider
        ... on ManualStatusProvider_v1 {
          manual {
            componentStatus
            from
            until
          }
        }
      }
    }
    maintenances {
      name
      message
      scheduledStart
      scheduledEnd
      affectedServices {
        name
      }
      announcements {
        provider
        ... on MaintenanceStatuspageAnnouncement_v1 {
          page {
            name
          }
          remindSubscribers
          notifySubscribersOnStart
          notifySubscribersOnCompletion
        }
      }
    }
  }
}
