# qenerate: plugin=pydantic_v1

fragment VPCRequest on VPCRequest_v1 {
  identifier
  delete
  account {
    name
    uid
    terraformUsername
    automationToken {
      ...VaultSecret
    }
    supportedDeploymentRegions
    resourcesDefaultRegion
    providerVersion
    terraformState {
      ...TerraformState
    }
    enableDeletion
    deletionApprovals {
      type
      name
      expiration
    }
  }
  region
  cidr_block {
    networkAddress
  }
  vpc_tags
  subnets {
    private
    public
    availability_zones
    private_subnet_tags
    public_subnet_tags
  }
}
