# qenerate: plugin=pydantic_v1

fragment AWSAccountManaged on AWSAccount_v1 {
  name
  uid
  alias
  terraformUsername
  premiumSupport
  organization {
    ou
    tags
  }
  quotaLimits {
    name
    quotas {
      serviceCode
      quotaCode
      value
    }
  }
}
