# qenerate: plugin=pydantic_v1

fragment AWSAccountCommon on AWSAccount_v1 {
  path
  name
  description
  uid
  terraformUsername
  consoleUrl
  resourcesDefaultRegion
  supportedDeploymentRegions
  providerVersion
  accountOwners {
    name
    email
  }
  automationToken {
    ... VaultSecret
  }
  enableDeletion
  deletionApprovals {
    type
    name
    expiration
  }
  disable {
    integrations
  }
  deleteKeys
  premiumSupport
  partition
}
