# qenerate: plugin=pydantic_v1

fragment VPCRequest on VPCRequest_v1 {
  name
  account {
    name
    uid
    terraformUsername
    automationToken {
      ...VaultSecret
    }
  }
  region
  cidr_block {
    networkAddress
  }
  subnets {
    private
    public
  }
}
