# qenerate: plugin=pydantic_v1

fragment RoleMembershipSource on RoleMembershipSource_V1 {
  group
  provider {
    name
    hasAuditTrail
    source {
      ... on AppInterfaceMembershipProviderSource_V1 {
        url
        username {
          ...VaultSecret
        }
        password {
          ...VaultSecret
        }
      }
    }
  }
}
