# qenerate: plugin=pydantic_v2

fragment OcConnectionCluster on Cluster_v1 {
  name
  serverUrl
  internal
  insecureSkipTLSVerify
  automationToken {
    ...VaultSecret
  }
  automationTokens {
    name
    namespace
    active
    delete
    secret {
      ...VaultSecret
    }
  }
  clusterAdminAutomationToken {
    ...VaultSecret
  }
  clusterAdminAutomationTokens {
    name
    namespace
    active
    delete
    secret {
      ...VaultSecret
    }
  }
  disable {
    integrations
  }
}
