# qenerate: plugin=pydantic_v2
fragment OCMEnvironment on OpenShiftClusterManagerEnvironment_v1 {
  name
  description
  labels
  url
  accessTokenClientId
  accessTokenUrl
  accessTokenClientSecret {
    ...VaultSecret
  }
}
