# qenerate: plugin=pydantic_v1
fragment OCMEnvironment on OpenShiftClusterManagerEnvironment_v1 {
    name
    labels
    url
    accessTokenClientId
    accessTokenUrl
    accessTokenClientSecret {
        ... VaultSecret
    }
}
