# qenerate: plugin=pydantic_v1

fragment SaasTargetNamespace on Namespace_v1 {
  name
  environment {
    name
    parameters
    secretParameters {
      name
      secret {
        ...VaultSecret
      }
    }
  }
  app {
    name
  }
  cluster {
    ...OcConnectionCluster
  }
}
