# qenerate: plugin=pydantic_v1

fragment SaasTargetNamespace on Namespace_v1 {
  name
  labels
  delete
  path
  environment {
    name
    labels
    parameters
    secretParameters {
      name
      secret {
        ...VaultSecret
      }
    }
  }
  app {
    name
    labels
  }
  cluster {
    ...OcConnectionCluster
  }
  skupperSite {
    delete
  }
}
