# qenerate: plugin=pydantic_v1

fragment ServiceAccountToken on ServiceAccountTokenSpec_v1 {
  name
  serviceAccountName
  namespace {
    name
    delete
    cluster {
      ...OcConnectionCluster
    }
  }
}
