# qenerate: plugin=pydantic_v1

fragment ServiceAccountToken on ServiceAccountTokenSpec_v1 {
    name
    namespace {
        name
        cluster {
            name
            serverUrl
            insecureSkipTLSVerify
            jumpHost {
                ... CommonJumphostFields
            }
            automationToken {
                ... VaultSecret
            }
            internal
            disable {
                integrations
            }
        }
    }
    serviceAccountName
}
