# qenerate: plugin=pydantic_v1

query ServiceAccountTokens {
  namespaces: namespaces_v1 {
    name
    cluster {
      name
      serverUrl
      insecureSkipTLSVerify
      jumpHost {
        ... CommonJumphostFields
      }
      automationToken {
        ... VaultSecret
      }
      internal
      disable {
        e2eTests
        integrations
      }
    }
    sharedResources {
      openshiftServiceAccountTokens {
        ... ServiceAccountToken
      }
    }
    openshiftServiceAccountTokens {
      ... ServiceAccountToken
    }
  }
}