"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


DEFINITION = """
query JiraServers {
  jira_servers: jira_servers_v1 {
    name
    description
    serverUrl
    username
    token {
      path
      version
      field
      format
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class VaultSecretV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")
    version: Optional[int] = Field(..., alias="version")
    field: str = Field(..., alias="field")
    q_format: Optional[str] = Field(..., alias="format")


class JiraServerV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    description: str = Field(..., alias="description")
    server_url: str = Field(..., alias="serverUrl")
    username: str = Field(..., alias="username")
    token: VaultSecretV1 = Field(..., alias="token")


class JiraServersQueryData(ConfiguredBaseModel):
    jira_servers: Optional[list[JiraServerV1]] = Field(..., alias="jira_servers")


def query(query_func: Callable, **kwargs: Any) -> JiraServersQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        JiraServersQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return JiraServersQueryData(**raw_data)
