FROM centos:7

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

RUN yum install -y epel-release && \
    yum install -y python36 python36-pip git && \
    python3.6 -m pip install --upgrade pip && \
    python3.6 -m pip install tox

COPY . /package
WORKDIR /package

CMD [ "tox" ]
