FROM quay.io/centos/centos:7

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

RUN yum install -y epel-release && \
    yum install -y python36 python36-pip git make gcc gcc-c++ python36-devel && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install tox

RUN curl -L https://get.helm.sh/helm-v3.6.2-linux-amd64.tar.gz |tar xvz && \
    mv linux-amd64/helm /usr/local/bin/helm && \
    chmod +x /usr/local/bin/helm && \
    rm -rf linux-amd64

COPY . /package
WORKDIR /package

CMD [ "tox" ]
