FROM centos/python-36-centos7

USER root

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

RUN python -m pip install --upgrade pip && \
    python -m pip install tox

COPY . /package
WORKDIR /package

CMD [ "tox" ]
