# qenerate: plugin=pydantic_v1

query TerraformRepo {
  repos: terraform_repo_v1 {
    account {
      name
      uid
      automationToken {
        ...VaultSecret
      }
      terraformState {
        provider
        bucket
        region
      }
    }
    name
    repository
    ref
    projectPath
    delete
  }
}
