# qenerate: plugin=pydantic_v1

query TerraformRepo {
  repos: terraform_repo_v1 {
    account {
      name
      uid
      automationToken {
        ...VaultSecret
      }
      terraformState {
        provider
        bucket
        region
        integrations {
          integration
          key
        }
      }
    }
    name
    app {
      name
    }
    repository
    ref
    projectPath
    delete
    requireFips
    tfVersion
    forceRerunTimestamp
    variables {
      inputs {
        ...VaultSecret
      }
      outputs {
        ...VaultSecret
      }
    }
  }
}
