# qenerate: plugin=pydantic_v2

query TerraformInitAWSAccounts {
  accounts: awsaccounts_v1 {
    name
    terraformUsername
    terraformState {
      bucket
      region
    }
    resourcesDefaultRegion
    automationToken {
      ...VaultSecret
    }
    disable {
      integrations
    }
    organization {
      ...AWSOrganization
    }
  }
}
