"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union = True
        extra = Extra.forbid


class NamespaceOpenshiftResource(ConfiguredBaseModel):
    provider: str = Field(..., alias="provider")


class ResourceV1(ConfiguredBaseModel):
    content: str = Field(..., alias="content")
    path: str = Field(..., alias="path")
    schema: Optional[str] = Field(..., alias="schema")


class NamespaceOpenshiftResourceResourceV1(NamespaceOpenshiftResource):
    resource: Optional[ResourceV1] = Field(..., alias="resource")
    validate_json: Optional[bool] = Field(..., alias="validate_json")
    validate_alertmanager_config: Optional[bool] = Field(
        ..., alias="validate_alertmanager_config"
    )
    alertmanager_config_key: Optional[str] = Field(..., alias="alertmanager_config_key")
    enable_query_support: Optional[bool] = Field(..., alias="enable_query_support")


class NamespaceOpenshiftResourceResourceTemplateV1_ResourceV1(ConfiguredBaseModel):
    content: str = Field(..., alias="content")
    path: str = Field(..., alias="path")
    schema: Optional[str] = Field(..., alias="schema")


class NamespaceOpenshiftResourceResourceTemplateV1(NamespaceOpenshiftResource):
    resource: Optional[NamespaceOpenshiftResourceResourceTemplateV1_ResourceV1] = Field(
        ..., alias="resource"
    )
    q_type: Optional[str] = Field(..., alias="type")
    variables: Optional[Json] = Field(..., alias="variables")
    validate_alertmanager_config: Optional[bool] = Field(
        ..., alias="validate_alertmanager_config"
    )
    alertmanager_config_key: Optional[str] = Field(..., alias="alertmanager_config_key")
    enable_query_support: Optional[bool] = Field(..., alias="enable_query_support")


class NamespaceOpenshiftResourceVaultSecretV1(NamespaceOpenshiftResource):
    path: str = Field(..., alias="path")
    version: int = Field(..., alias="version")
    name: Optional[str] = Field(..., alias="name")
    labels: Optional[Json] = Field(..., alias="labels")
    annotations: Optional[Json] = Field(..., alias="annotations")
    q_type: Optional[str] = Field(..., alias="type")
    validate_alertmanager_config: Optional[bool] = Field(
        ..., alias="validate_alertmanager_config"
    )
    alertmanager_config_key: Optional[str] = Field(..., alias="alertmanager_config_key")


class NamespaceOpenshiftResourceRouteV1_ResourceV1(ConfiguredBaseModel):
    content: str = Field(..., alias="content")
    path: str = Field(..., alias="path")
    schema: Optional[str] = Field(..., alias="schema")


class NamespaceOpenshiftResourceRouteV1(NamespaceOpenshiftResource):
    resource: Optional[NamespaceOpenshiftResourceRouteV1_ResourceV1] = Field(
        ..., alias="resource"
    )
    vault_tls_secret_path: Optional[str] = Field(..., alias="vault_tls_secret_path")
    vault_tls_secret_version: Optional[int] = Field(
        ..., alias="vault_tls_secret_version"
    )
