# qenerate: plugin=pydantic_v2

query AppSRETektonAccessRevalidationRoles {
  roles: roles_v1 {
    path
    access {
      clusterRole
      namespace {
        path
      }
    }
    users {
      org_username
      path
    }
  }
}
