# qenerate: plugin=pydantic_v2

query AppSRETektonAccessRevalidationUsers {
  users: users_v1 {
    name
    org_username
    roles {
      access {
        clusterRole
        namespace {
          name
          cluster {
            name
          }
        }
      }
    }
  }
}
