# qenerate: plugin=pydantic_v2

query ManagedSsoClient {
  managed_sso_clients: managed_sso_clients_v1 {
    name
    description
    enabled
    app {
      name
    }
    protocol
    keycloakInstance {
      url
      initialAccessToken {
        ...VaultSecret
      }
    }
    output
    ... on ManagedSsoClientOpenidConnect_v1 {
      oidc {
        accessType
        directAccessGrantsEnabled
        serviceAccountsEnabled
        redirectUris
        postLogoutRedirectUris
        webOrigins
        consentRequired
        fullScopeAllowed
        defaultClientScopes
        optionalClientScopes
      }
    }
  }
}
