# qenerate: plugin=pydantic_v1

query AcsInstance {
  instances: acs_instance_v1 {
    url
    token {
      ... on VaultSecret_v1 {
        path
        field
        version
      }
    }
    authProvider {
      ... on AcsInstanceAuthProvider_v1 {
        name
        id
      }
    }
  }
}
