# qenerate: plugin=pydantic_v1

query AcsRbac  {
  acs_rbacs: users_v1 {
    acs_user
    roles {
      name
      oidc_permissions {
        name
        description
        service
        ... on OidcPermissionAcs_v1 {
          permission_set
          clusters {
            name
          }
          namespaces {
            name
            cluster {
              name
            }
          }
        }
      }
    }
  }
}
