"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


DEFINITION = """
query AcsPolicy {
  acs_policies: acs_policy_v1 {
   	name 
    severity
    categories
    scope {
      level
      ... on AcsPolicyScopeCluster_v1 {
		clusters {
          name
        }        
      }
      ... on AcsPolicyScopeNamespace_v1 {
       	namespaces {
          name
        }
      }
    }
	conditions {
      cvss {
        comparison
        score
      }
      severity {
        comparison
        level
      }
      imageTag {
        values
        negate
      }
      imageAge
      fixableCve
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class AcsPolicyScopeV1(ConfiguredBaseModel):
    level: str = Field(..., alias="level")


class ClusterV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")


class AcsPolicyScopeClusterV1(AcsPolicyScopeV1):
    clusters: list[ClusterV1] = Field(..., alias="clusters")


class NamespaceV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")


class AcsPolicyScopeNamespaceV1(AcsPolicyScopeV1):
    namespaces: list[NamespaceV1] = Field(..., alias="namespaces")


class AcsPolicyConditionsCvssV1(ConfiguredBaseModel):
    comparison: str = Field(..., alias="comparison")
    score: int = Field(..., alias="score")


class AcsPolicyConditionsSeverityV1(ConfiguredBaseModel):
    comparison: str = Field(..., alias="comparison")
    level: str = Field(..., alias="level")


class AcsPolicyConditionsImageTagV1(ConfiguredBaseModel):
    values: list[str] = Field(..., alias="values")
    negate: Optional[bool] = Field(..., alias="negate")


class AcsPolicyConditionsV1(ConfiguredBaseModel):
    cvss: Optional[AcsPolicyConditionsCvssV1] = Field(..., alias="cvss")
    severity: Optional[AcsPolicyConditionsSeverityV1] = Field(..., alias="severity")
    image_tag: Optional[AcsPolicyConditionsImageTagV1] = Field(..., alias="imageTag")
    image_age: Optional[int] = Field(..., alias="imageAge")
    fixable_cve: Optional[bool] = Field(..., alias="fixableCve")


class AcsPolicyV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    severity: str = Field(..., alias="severity")
    categories: list[str] = Field(..., alias="categories")
    scope: Union[AcsPolicyScopeClusterV1, AcsPolicyScopeNamespaceV1, AcsPolicyScopeV1] = Field(..., alias="scope")
    conditions: AcsPolicyConditionsV1 = Field(..., alias="conditions")


class AcsPolicyQueryData(ConfiguredBaseModel):
    acs_policies: Optional[list[AcsPolicyV1]] = Field(..., alias="acs_policies")


def query(query_func: Callable, **kwargs: Any) -> AcsPolicyQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        AcsPolicyQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return AcsPolicyQueryData(**raw_data)
