"""
Generated by qenerate plugin=pydantic_v2. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    ConfigDict,
    Field,
    Json,
)

from reconcile.gql_definitions.fragments.aws_account_common import AWSAccountCommon
from reconcile.gql_definitions.fragments.aws_infra_management_account import AWSInfrastructureManagementAccount
from reconcile.gql_definitions.fragments.ocm_environment import OCMEnvironment
from reconcile.gql_definitions.fragments.membership_source import RoleMembershipSource
from reconcile.gql_definitions.fragments.vault_secret import VaultSecret


DEFINITION = """
fragment AWSAccountCommon on AWSAccount_v1 {
  path
  name
  description
  uid
  terraformUsername
  consoleUrl
  resourcesDefaultRegion
  supportedDeploymentRegions
  providerVersion
  accountOwners {
    name
    email
  }
  automationToken {
    ...VaultSecret
  }
  enableDeletion
  deletionApprovals {
    type
    name
    expiration
  }
  disable {
    integrations
  }
  deleteKeys
  premiumSupport
  partition
  organization {
    ...AWSOrganization
  }
}

fragment AWSInfrastructureManagementAccount on AWSInfrastructureManagementAccount_v1 {
  account {
    name
    uid
    terraformUsername
    resourcesDefaultRegion
    automationToken {
      ...VaultSecret
    }
  }
  accessLevel
  default
}

fragment AWSOrganization on AWSOrganization_v1 {
  payerAccount {
    organizationAccountTags
  }
  tags
}

fragment OCMEnvironment on OpenShiftClusterManagerEnvironment_v1 {
  name
  description
  labels
  url
  accessTokenClientId
  accessTokenUrl
  accessTokenClientSecret {
    ...VaultSecret
  }
}

fragment RoleMembershipSource on RoleMembershipSource_V1 {
  group
  provider {
    name
    hasAuditTrail
    source {
      provider
      ... on AppInterfaceMembershipProviderSource_V1 {
        url
        username {
          ...VaultSecret
        }
        password {
          ...VaultSecret
        }
      }
    }
  }
}

fragment VaultSecret on VaultSecret_v1 {
  url
  path
  field
  version
  format
}

query InfrastructureAccessClusters {
  clusters: clusters_v1 {
    name
    disable {
      integrations
    }
    spec {
      product
    }
    ocm {
      name
      environment {
        ...OCMEnvironment
      }
      orgId
      accessTokenClientId
      accessTokenUrl
      accessTokenClientSecret {
        ...VaultSecret
      }
    }
    awsInfrastructureAccess {
      accessLevel
      awsGroup {
        account {
          ...AWSAccountCommon
        }
        roles {
          name
          users {
            org_username
            aws_username
          }
          memberSources {
            ...RoleMembershipSource
          }
        }
      }
    }
    awsInfrastructureManagementAccounts {
      ...AWSInfrastructureManagementAccount
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid'
    )


class DisableClusterAutomationsV1(ConfiguredBaseModel):
    integrations: Optional[list[str]] = Field(..., alias="integrations")


class ClusterSpecV1(ConfiguredBaseModel):
    product: str = Field(..., alias="product")


class OpenShiftClusterManagerV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    environment: OCMEnvironment = Field(..., alias="environment")
    org_id: str = Field(..., alias="orgId")
    access_token_client_id: Optional[str] = Field(..., alias="accessTokenClientId")
    access_token_url: Optional[str] = Field(..., alias="accessTokenUrl")
    access_token_client_secret: Optional[VaultSecret] = Field(..., alias="accessTokenClientSecret")


class UserV1(ConfiguredBaseModel):
    org_username: str = Field(..., alias="org_username")
    aws_username: Optional[str] = Field(..., alias="aws_username")


class RoleV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    users: list[UserV1] = Field(..., alias="users")
    member_sources: Optional[list[RoleMembershipSource]] = Field(..., alias="memberSources")


class AWSGroupV1(ConfiguredBaseModel):
    account: AWSAccountCommon = Field(..., alias="account")
    roles: Optional[list[RoleV1]] = Field(..., alias="roles")


class AWSInfrastructureAccessV1(ConfiguredBaseModel):
    access_level: str = Field(..., alias="accessLevel")
    aws_group: AWSGroupV1 = Field(..., alias="awsGroup")


class ClusterV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    disable: Optional[DisableClusterAutomationsV1] = Field(..., alias="disable")
    spec: Optional[ClusterSpecV1] = Field(..., alias="spec")
    ocm: Optional[OpenShiftClusterManagerV1] = Field(..., alias="ocm")
    aws_infrastructure_access: Optional[list[AWSInfrastructureAccessV1]] = Field(..., alias="awsInfrastructureAccess")
    aws_infrastructure_management_accounts: Optional[list[AWSInfrastructureManagementAccount]] = Field(..., alias="awsInfrastructureManagementAccounts")


class InfrastructureAccessClustersQueryData(ConfiguredBaseModel):
    clusters: Optional[list[ClusterV1]] = Field(..., alias="clusters")


def query(query_func: Callable, **kwargs: Any) -> InfrastructureAccessClustersQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        InfrastructureAccessClustersQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return InfrastructureAccessClustersQueryData(**raw_data)
