# qenerate: plugin=pydantic_v1

query CNAssets {
  namespaces: namespaces_v1 {
    name
    externalResources {
      provider
      provisioner {
        name
      }
      ... on NamespaceCNAsset_v1 {
        resources {
          provider
          ... on CNANullAsset_v1 {
            name: identifier
            addr_block
          }
          ... on CNAAssumeRoleAsset_v1{
            name: identifier
            aws_assume_role {
              slug
              account {
                ... CNAAWSAccountRoleARNs
              }
            }
          }
          ... on CNARDSInstance_v1 {
            name: identifier
            vpc {
              vpc_id
              region
              account {
                ... CNAAWSAccountRoleARNs
              }
            }
            defaults
            overrides {
              name
              engine
              engine_version
              username
              instance_class
              allocated_storage
              max_allocated_storage
              backup_retention_period
              db_subnet_group_name
            }
          }
        }
      }
    }
  }
}
