# qenerate: plugin=pydantic_v1

query CNAssets {
  namespaces: namespaces_v1 {
    name
    cluster {
      spec {
        id
      }
    }
    managedExternalResources
    externalResources {
      provider
      provisioner {
        name
      }
      ... on NamespaceCNAsset_v1 {
        resources {
          provider
          identifier
          ... on CNANullAsset_v1 {
            defaults {
              addr_block
            }
            overrides
          }
          ... on CNARDSInstance_v1 {
            name
            defaults {
              vpc {
                vpc_id
                region
                account {
                  ... CNAAWSAccountRoleARNs
                }
              }
              db_subnet_group_name
              instance_class
              allocated_storage
              max_allocated_storage
              engine
              engine_version
              username
              maintenance_window
              backup_retention_period
              backup_window
              multi_az
              deletion_protection
              apply_immediately
            }
            overrides
          }
          ... on CNAAssumeRoleAsset_v1{
            aws_account {
              ... CNAAWSAccountRoleARNs
            }
            defaults {
              slug
            }
            overrides
          }
        }
      }
    }
  }
}
