# qenerate: plugin=pydantic_v2
query GcpProjects {
  gcp_projects: gcp_projects_v1 {
    name
    gcrPushCredentials {
      ...VaultSecret
    }
    artifactPushCredentials {
      ...VaultSecret
    }
  }
}
