# qenerate: plugin=pydantic_v1

query VaultInstances {
  vault_instances: vault_instances_v1 {
    name
    address
    auth {
      provider
      secretEngine
      ... on VaultInstanceAuthApprole_v1 {
      roleID {
        path
        field
      }
      secretID {
        path
        field
      }
    }
    }
    replication {
      vaultInstance {
        name
        address
        auth {
            provider
            secretEngine
            ... on VaultInstanceAuthApprole_v1 {
              roleID {
                path
                field
              }
              secretID {
                path
                field
              }
            }
          }
      }
      paths {
        provider
        ...on VaultReplicationJenkins_v1 {
        jenkinsInstance {
          name
          serverUrl
        }
        policy {
          name
          instance {
            name
            address
          }
        }
        }
      }
    }
  }
}
