# qenerate: plugin=pydantic_v2

query OpenshiftClusterBotsQuery($name: String) {
  clusters: clusters_v1(name: $name) {
    name
    path
    serverUrl
    ocm {
      name
      environment {
        ...OCMEnvironment
      }
      orgId
      accessTokenClientId
      accessTokenUrl
      accessTokenClientSecret {
        ...VaultSecret
      }
    }
    automationToken {  # TODO(APPSRE-13941): remove once all clusters migrated to automationTokens
      ...VaultSecret
    }
    automationTokens {
      name
      namespace
      active
      delete
      secret {
        ...VaultSecret
      }
    }
    clusterAdmin
    clusterAdminAutomationToken {  # TODO(APPSRE-13941): remove once all clusters migrated to clusterAdminAutomationTokens
      ...VaultSecret
    }
    clusterAdminAutomationTokens {
      name
      namespace
      active
      delete
      secret {
        ...VaultSecret
      }
    }
    disable {
      integrations
    }
  }
}
