# qenerate: plugin=pydantic_v1

query OpenshiftClusterBotsQuery($name: String) {
  clusters: clusters_v1(name: $name) {
    name
    path
    serverUrl
    ocm {
      name
      environment {
        ... OCMEnvironment
      }
      orgId
      accessTokenClientId
      accessTokenUrl
      accessTokenClientSecret {
        ... VaultSecret
      }
    }
    automationToken {
      ... VaultSecret
    }
    clusterAdmin
    clusterAdminAutomationToken {
      ... VaultSecret
    }
    disable {
      integrations
    }
  }
}
