# qenerate: plugin=pydantic_v1

query ChangeTypes {
  change_types: change_types_v1 {
    name
    contextType
    contextSchema
    changes {
      provider
      changeSchema
      context {
        selector
        when
      }
      ... on ChangeTypeChangeDetectorJsonPathProvider_v1 {
        jsonPathSelectors
      }
    }
  }
}
