# qenerate: plugin=pydantic_v1

query ChangeTypes($name: String) {
  change_types: change_types_v1(name: $name) {
    name
    description
    priority
    contextType
    contextSchema
    disabled
    changes {
      provider
      changeSchema
      context {
        selector
        when
      }
      ... on ChangeTypeChangeDetectorJsonPathProvider_v1 {
        jsonPathSelectors
        jsonPathSelectorTemplates {
          var
          items
          template
        }
      }
    }
    inherit {
      name
    }
  }
}
