# qenerate: plugin=pydantic_v1

query ChangeTypes($name: String) {
  change_types: change_types_v1(name: $name) {
    name
    description
    priority
    contextType
    contextSchema
    disabled
    restrictive
    changes {
      provider
      changeSchema
      ... on ChangeTypeChangeDetectorJsonPathProvider_v1 {
        jsonPathSelectors
        context {
          selector
          when
          where
        }
      }
      ... on ChangeTypeChangeDetectorChangeTypeProvider_v1 {
        changeTypes {
          name
          contextSchema
        }
        ownership_context: context {
          selector
          when
          where
        }
      }
    }
    implicitOwnership {
      provider
      ... on ChangeTypeImplicitOwnershipJsonPathProvider_v1 {
        jsonPathSelector
      }
    }
    inherit {
      name
    }
  }
}
