# qenerate: plugin=pydantic_v1

query SelfServiceRolesQuery {
  roles: roles_v1 {
    name
    path
    self_service {
      change_type {
        name
      }
      datafiles {
        datafileSchema: schema
        path
      }
      datafileProviders {
        provider
        ... on ResourceTemplateDatafileProvider_v1 {
          template: path {
            content
          }
          template_format: type
          variables
          enable_query_support
        }
      }
      resources
    }
    users {
      org_username
      tag_on_merge_requests
    }
    bots {
      org_username
    }
  }
}
