---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/qontract-reconcile?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: (event == "pull_request" && target_branch == "master") || (event == "push" && target_branch.startsWith("gh-readonly-queue/master/"))
  labels:
    appstudio.openshift.io/application: qontract-reconcile-master
    appstudio.openshift.io/component: qontract-api-client-master
    pipelines.appstudio.openshift.io/type: build
  name: qontract-api-client-master-on-pull-request
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/qontract-reconcile-master/qontract-api-client-master:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: qontract_api_client/Dockerfile
  - name: path-context
    value: .
  - name: target-stage
    value: test
  pipelineName: qontract-api-client-pull-request
  pipelineRef:
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
    resolver: git
  taskRunSpecs:
  - pipelineTaskName: "*"
    computeResources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        memory: "2Gi"
  taskRunTemplate:
    serviceAccountName: build-pipeline-qontract-api-client-master
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
