---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/qontract-reconcile?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # run on the same push as the primary non-fips build
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "master"
  labels:
    appstudio.openshift.io/application: qontract-reconcile-master
    appstudio.openshift.io/component: qontract-reconcile-fips-master
    pipelines.appstudio.openshift.io/type: build
  name: qontract-reconcile-fips-master-on-push
  namespace: app-sre-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/app-sre-tenant/qontract-reconcile-master/qontract-reconcile-fips-master:{{revision}}
    - name: dockerfile
      value: dockerfiles/Dockerfile
    - name: path-context
      value: .
    - name: target-stage
      value: fips-prod-image
    - name: fetchTags
      value: 'true'
    - name: cloneDepth
      value: '100000'
    - name: goss-container-structure-test-file
      value: dockerfiles/goss.yaml
  pipelineRef:
    params:
      - name: url
        value: https://github.com/app-sre/shared-pipelines
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/multi-arch-build-pipeline.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-qontract-reconcile-master
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
