# qenerate: plugin=pydantic_v2

query AppQuayReposEscalationPolicies {
  apps: apps_v1 {
    name
    parentApp {
      name
    }
    escalationPolicy {
      channels {
        email
        slackUserGroup {
          handle
        }
      }
    }
    quayRepos {
      org {
        name
      }
      items {
        name
        mirror {
          path
        }
      }
    }
  }
}
