"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


DEFINITION = """
query AppQuayReposEscalationPolicies {
  apps: apps_v1 {
    name
    parentApp {
      name
    }
    escalationPolicy {
      channels {
        email
        slackUserGroup {
          handle
        }
      }
    }
    quayRepos {
      org {
        name
      }
      items {
        name
        mirror {
          path
        }
      }
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class AppV1_AppV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")


class PermissionSlackUsergroupV1(ConfiguredBaseModel):
    handle: str = Field(..., alias="handle")


class AppEscalationPolicyChannelsV1(ConfiguredBaseModel):
    email: list[str] = Field(..., alias="email")
    slack_user_group: list[PermissionSlackUsergroupV1] = Field(..., alias="slackUserGroup")


class AppEscalationPolicyV1(ConfiguredBaseModel):
    channels: AppEscalationPolicyChannelsV1 = Field(..., alias="channels")


class QuayOrgV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")


class ContainerImageMirrorV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")


class AppQuayReposItemsV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    mirror: Optional[ContainerImageMirrorV1] = Field(..., alias="mirror")


class AppQuayReposV1(ConfiguredBaseModel):
    org: QuayOrgV1 = Field(..., alias="org")
    items: list[AppQuayReposItemsV1] = Field(..., alias="items")


class AppV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    parent_app: Optional[AppV1_AppV1] = Field(..., alias="parentApp")
    escalation_policy: AppEscalationPolicyV1 = Field(..., alias="escalationPolicy")
    quay_repos: Optional[list[AppQuayReposV1]] = Field(..., alias="quayRepos")


class AppQuayReposEscalationPoliciesQueryData(ConfiguredBaseModel):
    apps: Optional[list[AppV1]] = Field(..., alias="apps")


def query(query_func: Callable, **kwargs: Any) -> AppQuayReposEscalationPoliciesQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        AppQuayReposEscalationPoliciesQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return AppQuayReposEscalationPoliciesQueryData(**raw_data)
