# qenerate: plugin=pydantic_v2

query ClustersWithMonitoring($filter: JSON) {
  clusters: clusters_v1(filter: $filter) {
    name
    serverUrl
    consoleUrl
    alertmanagerUrl
    prometheusUrl
    managedClusterRoles
    enableDeadMansSnitch
  }
}
