# qenerate: plugin=pydantic_v1

query ClustersWithMonitoring{
  clusters: clusters_v1{
    name
    serverUrl
    consoleUrl
    alertmanagerUrl
    prometheusUrl
    managedClusterRoles
    enableDeadMansSnitch
  }
}
