# qenerate: plugin=pydantic_v1

query PgpReencryptionSettings {
  pgp_reencryption_settings: pgp_reencrypt_settings_v1{
    public_gpg_key
    aws_account_output_vault_path
    reencrypt_vault_path
    skip_aws_accounts {
      name
    }
  }
}