# qenerate: plugin=pydantic_v2

query PipelineProviders {
  pipelines_providers: pipelines_providers_v1 {
    name
    provider
    ... on PipelinesProviderTekton_v1 {
      defaults {
        taskTemplates {
          ... on PipelinesProviderTektonObjectTemplate_v1 {
            name
            type
            path
            variables
          }
        }
        pipelineTemplates {
          openshiftSaasDeploy {
            name
            type
            path
            variables
          }
        }
        deployResources {
          requests {
            ...ResourceRequestsRequirements
          }
          limits {
            ...ResourceLimitsRequirements
          }
        }
      }
      namespace {
        name
        path
        clusterAdmin
        app {
          name
          path
        }
        cluster {
          name
          serverUrl
          insecureSkipTLSVerify
          automationToken {
            ...VaultSecret
          }
          automationTokens {
            name
            namespace
            active
            delete
            secret {
              ...VaultSecret
            }
          }
          clusterAdminAutomationToken {
            ...VaultSecret
          }
          clusterAdminAutomationTokens {
            name
            namespace
            active
            delete
            secret {
              ...VaultSecret
            }
          }
          internal
          disable {
            integrations
          }
        }
      }
      taskTemplates {
        ... on PipelinesProviderTektonObjectTemplate_v1 {
          name
          type
          path
          variables
        }
      }
      pipelineTemplates {
        openshiftSaasDeploy {
          name
          type
          path
          variables
        }
      }
      deployResources {
        requests {
          ...ResourceRequestsRequirements
        }
        limits {
          ...ResourceLimitsRequirements
        }
      }
    }
  }
}
