# qenerate: plugin=pydantic_v2

query ReservedNetworks {
  networks: network_v1 {
    name
    networkAddress
    parentNetwork {
      networkAddress
    }
    inUseBy {
      vpc {
        account {
          name
          uid
          consoleUrl
        }
      }
    }
  }
}
