# qenerate: plugin=pydantic_v2

query SaasherderSettings {
  settings: app_interface_settings_v1 {
    repoUrl
    hashLength
    imagePatternsBlockRules {
      environmentLabelSelector
      imagePatterns
    }
  }
}
