# qenerate: plugin=pydantic_v1

 query AppInterfaceSmtpSettings {
   settings: app_interface_settings_v1 {
     smtp {
       mailAddress
       timeout
       credentials {
         ... VaultSecret
       }
     }
   }
 }
