# qenerate: plugin=pydantic_v1

query StateAwsAccount($name: String) {
  accounts: awsaccounts_v1(name: $name) {
    name
    resourcesDefaultRegion
    automationToken {
      path
      field
      version
      format
    }
  }
}
