"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


DEFINITION = """
query UsersWithPaths {
  users: users_v1 {
    path
    org_username
    aws_accounts {
      path
    }
    requests {
      path
    }
    queries {
      path
    }
    gabi_instances {
      path
    }
    schedules {
      path
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class AWSAccountV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")


class CredentialsRequestV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")


class AppInterfaceSqlQueryV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")


class GabiInstanceV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")


class ScheduleV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")


class UserV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")
    org_username: str = Field(..., alias="org_username")
    aws_accounts: Optional[list[AWSAccountV1]] = Field(..., alias="aws_accounts")
    requests: Optional[list[CredentialsRequestV1]] = Field(..., alias="requests")
    queries: Optional[list[AppInterfaceSqlQueryV1]] = Field(..., alias="queries")
    gabi_instances: Optional[list[GabiInstanceV1]] = Field(..., alias="gabi_instances")
    schedules: Optional[list[ScheduleV1]] = Field(..., alias="schedules")


class UsersWithPathsQueryData(ConfiguredBaseModel):
    users: Optional[list[UserV1]] = Field(..., alias="users")


def query(query_func: Callable, **kwargs: Any) -> UsersWithPathsQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        UsersWithPathsQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return UsersWithPathsQueryData(**raw_data)
