# qenerate: plugin=pydantic_v2

query UsersWithPaths {
  users: users_v1 {
    path
    org_username
    aws_accounts {
      path
    }
    requests {
      path
    }
    queries {
      path
    }
    gabi_instances {
      path
    }
    schedules {
      path
    }
  }
}
