# qenerate: plugin=pydantic_v1

query SlackUsergroupPermission {
  permissions: permissions_v1 {
    service
    ... on PermissionSlackUsergroup_v1 {
      name
      channels
      description
      handle
      ownersFromRepos
      skip
      pagerduty {
        name
        instance {
          name
        }
        scheduleID
        escalationPolicyID
      }
      roles {
        users {
          ...User
        }
      }
      schedule {
        schedule {
          start
          end
          users {
            ...User
          }
        }
      }
      workspace {
        name
        api_client {
          global {
            max_retries
            timeout
          }
          methods {
            name
            args
          }
        }
        integrations {
          name
          token {
            ...VaultSecret
          }
          channel
        }
        managedUsergroups
      }
    }
  }
}
