"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


DEFINITION = """
query TemplatingConfigurationV1{
  templating_configuration_v1{
    name
    parentObjects{
      parentFile
      parentQuery {
        query
        selector
      }
    }
    variables
    templates {
      targetPath
      template
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class TemplatingConfigurationParentObjectQueryV1(ConfiguredBaseModel):
    query: str = Field(..., alias="query")
    selector: Optional[str] = Field(..., alias="selector")


class TemplatingConfigurationParentObjectV1(ConfiguredBaseModel):
    parent_file: Optional[str] = Field(..., alias="parentFile")
    parent_query: Optional[TemplatingConfigurationParentObjectQueryV1] = Field(..., alias="parentQuery")


class TemplateV1(ConfiguredBaseModel):
    target_path: str = Field(..., alias="targetPath")
    template: str = Field(..., alias="template")


class TemplatingConfigurationV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    parent_objects: list[TemplatingConfigurationParentObjectV1] = Field(..., alias="parentObjects")
    variables: Json = Field(..., alias="variables")
    templates: list[TemplateV1] = Field(..., alias="templates")


class TemplatingConfigurationV1QueryData(ConfiguredBaseModel):
    templating_configuration_v1: Optional[list[TemplatingConfigurationV1]] = Field(..., alias="templating_configuration_v1")


def query(query_func: Callable, **kwargs: Any) -> TemplatingConfigurationV1QueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        TemplatingConfigurationV1QueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return TemplatingConfigurationV1QueryData(**raw_data)
