# qenerate: plugin=pydantic_v1

query TemplateCollection_v1($name: String) {
  template_collection_v1(name: $name) {
    name
    additionalMrLabels
    description
    enableAutoApproval
    forEach {
      items
    }
    variables {
      static
      dynamic {
        name
        query
      }
    }
    templates {
      name
      autoApproved
      condition
      targetPath
      overwrite
      patch {
        path
        identifier
      }
      template
      templateRenderOptions {
        trimBlocks
        lstripBlocks
        keepTrailingNewline
      }
    }
  }
}
