"""
Generated by qenerate plugin=pydantic_v2. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    ConfigDict,
    Field,
    Json,
)


DEFINITION = """
query GithubOwnersApiRoles {
  roles: roles_v1 {
    name
    users {
      github_username
    }
    bots {
      github_username
    }
    permissions {
      service
      ... on PermissionGithubOrg_v1 {
        org
        role
      }
      ... on PermissionGithubOrgTeam_v1 {
        org
        role
      }
    }
    expirationDate
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid'
    )


class UserV1(ConfiguredBaseModel):
    github_username: str = Field(..., alias="github_username")


class BotV1(ConfiguredBaseModel):
    github_username: Optional[str] = Field(..., alias="github_username")


class PermissionV1(ConfiguredBaseModel):
    service: str = Field(..., alias="service")


class PermissionGithubOrgV1(PermissionV1):
    org: str = Field(..., alias="org")
    role: Optional[str] = Field(..., alias="role")


class PermissionGithubOrgTeamV1(PermissionV1):
    org: str = Field(..., alias="org")
    role: Optional[str] = Field(..., alias="role")


class RoleV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    users: list[UserV1] = Field(..., alias="users")
    bots: list[BotV1] = Field(..., alias="bots")
    permissions: Optional[list[Union[PermissionGithubOrgV1, PermissionGithubOrgTeamV1, PermissionV1]]] = Field(..., alias="permissions")
    expiration_date: Optional[str] = Field(..., alias="expirationDate")


class GithubOwnersApiRolesQueryData(ConfiguredBaseModel):
    roles: Optional[list[RoleV1]] = Field(..., alias="roles")


def query(query_func: Callable, **kwargs: Any) -> GithubOwnersApiRolesQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        GithubOwnersApiRolesQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return GithubOwnersApiRolesQueryData(**raw_data)
