# qenerate: plugin=pydantic_v2
query GithubOwnersApiRoles {
  roles: roles_v1 {
    name
    users {
      github_username
    }
    bots {
      github_username
    }
    permissions {
      ... on PermissionGithubOrgTeam_v1 {
        service
        org
        role
      }
    }
    expirationDate
  }
}
