# qenerate: plugin=pydantic_v2

query AwsSamlRolesQuery {
  roles: roles_v1 {
    name
    user_policies {
      name
      policy
      account {
        ...AWSAccountSSO
      }
    }
    aws_groups {
      account {
        ...AWSAccountSSO
      }
      policies
    }
  }
}
