# qenerate: plugin=pydantic_v1

query EndPointsDiscoveryApps {
  apps: apps_v1 {
    path
    name
    endPoints {
      name
      url
    }
    namespaces {
      name
      delete
      clusterAdmin
      cluster {
        ...OcConnectionCluster
      }
    }
  }
}
