# qenerate: plugin=pydantic_v1

query EndPointsDiscoveryNamespaces {
  namespaces: namespaces_v1 {
    name
    delete
    clusterAdmin
    cluster {
      ... OcConnectionCluster
    }
    app {
      path
      name
      endPoints {
        name
        url
      }
    }
  }
}
