# qenerate: plugin=pydantic_v2

query ServiceAccountTokens {
  namespaces: namespaces_v1 {
    name
    delete
    cluster {
      ...OcConnectionCluster
    }
    sharedResources {
      openshiftServiceAccountTokens {
        ...ServiceAccountToken
      }
    }
    openshiftServiceAccountTokens {
      ...ServiceAccountToken
    }
  }
}
