---
# Source: qontract-reconcile/templates/template.yaml
apiVersion: v1
kind: Template
metadata:
  name: qontract-reconcile
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: qontract-reconcile
    name: qontract-reconcile
  spec:
    replicas: 1
    selector:
      app: qontract-reconcile
      deploymentconfig: qontract-reconcile
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: qontract-reconcile
          deploymentconfig: qontract-reconcile
      spec:
        containers:
        - name: aws-garbage-collector
          image: ${IMAGE}:${IMAGE_TAG}
          command: ["/bin/sh"]
          args: ["-c", "while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} aws-garbage-collector; sleep ${SLEEP_DURATION_SECS}; done"]
          resources:
            requests:
              memory: 800Mi
              cpu: 100m
            limits:
              memory: 800Mi
              cpu: 100m
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: aws-iam-keys
          image: ${IMAGE}:${IMAGE_TAG}
          command: ["/bin/sh"]
          args: ["-c", "while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} aws-iam-keys; sleep ${SLEEP_DURATION_SECS}; done"]
          resources:
            requests:
              memory: 100Mi
              cpu: 25m
            limits:
              memory: 100Mi
              cpu: 25m
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: github
          image: ${IMAGE}:${IMAGE_TAG}
          command: ["/bin/sh"]
          args: ["-c", "while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} github; sleep ${SLEEP_DURATION_SECS}; done"]
          resources:
            requests:
              memory: 100Mi
              cpu: 25m
            limits:
              memory: 100Mi
              cpu: 25m
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: github-repo-invites
          image: ${IMAGE}:${IMAGE_TAG}
          command: ["/bin/sh"]
          args: ["-c", "while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} github-repo-invites; sleep ${SLEEP_DURATION_SECS}; done"]
          resources:
            requests:
              memory: 100Mi
              cpu: 25m
            limits:
              memory: 100Mi
              cpu: 25m
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: quay-membership
          image: ${IMAGE}:${IMAGE_TAG}
          command: ["/bin/sh"]
          args: ["-c", "while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} quay-membership; sleep ${SLEEP_DURATION_SECS}; done"]
          resources:
            requests:
              memory: 100Mi
              cpu: 25m
            limits:
              memory: 100Mi
              cpu: 25m
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: slack-usergroups
          image: ${IMAGE}:${IMAGE_TAG}
          command: ["/bin/sh"]
          args: ["-c", "while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} slack-usergroups; sleep ${SLEEP_DURATION_SECS}; done"]
          resources:
            requests:
              memory: 100Mi
              cpu: 25m
            limits:
              memory: 100Mi
              cpu: 25m
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        volumes:
        - name: qontract-reconcile-toml
          secret:
            secretName: qontract-reconcile-toml
parameters:
- name: IMAGE
  value: quay.io/app-sre/qontract-reconcile
- name: IMAGE_TAG
  value: latest
- name: DRY_RUN
  value: --dry-run
- name: SLEEP_DURATION_SECS
  value: "300"
