---
apiVersion: v1
kind: Template
metadata:
  name: qontract-reconcile
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: qontract-reconcile
    name: qontract-reconcile
  spec:
    replicas: 1
    selector:
      app: qontract-reconcile
      deploymentconfig: qontract-reconcile
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: qontract-reconcile
          deploymentconfig: qontract-reconcile
      spec:
        containers:
        - name: slack-usergroups
          image: ${IMAGE}:${IMAGE_TAG}
          command: ["/bin/sh"]
          args: ["-c", "while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} slack-usergroups; sleep 30; done"]
          resources:
            requests:
              memory: 256Mi
              cpu: 300m
            limits:
              memory: 256Mi
              cpu: 300m
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        volumes:
        - name: qontract-reconcile-toml
          secret:
            secretName: qontract-reconcile-toml
parameters:
- name: IMAGE
  value: quay.io/app-sre/qontract-reconcile
- name: IMAGE_TAG
  value: latest
- name: DRY_RUN
  value: --dry-run
