---
# Source: qontract-reconcile/templates/template.yaml
apiVersion: v1
kind: Template
metadata:
  name: qontract-reconcile
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: qontract-reconcile
    name: qontract-reconcile
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: qontract-reconcile
    template:
      metadata:
        labels:
          app: qontract-reconcile
      spec:
        containers:
        - name: aws-garbage-collector
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /bin/sh
          - -c
          - while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} aws-garbage-collector ; sleep ${SLEEP_DURATION_SECS}; done
          resources:
            limits:
              cpu: 50m
              memory: 400Mi
            requests:
              cpu: 25m
              memory: 200Mi
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: github
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /bin/sh
          - -c
          - while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} github ; sleep ${SLEEP_DURATION_SECS}; done
          resources:
            limits:
              cpu: 25m
              memory: 80Mi
            requests:
              cpu: 15m
              memory: 50Mi
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: github-repo-invites
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /bin/sh
          - -c
          - while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} github-repo-invites ; sleep ${SLEEP_DURATION_SECS}; done
          resources:
            limits:
              cpu: 25m
              memory: 55Mi
            requests:
              cpu: 15m
              memory: 30Mi
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: quay-membership
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /bin/sh
          - -c
          - while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} quay-membership ; sleep ${SLEEP_DURATION_SECS}; done
          resources:
            limits:
              cpu: 25m
              memory: 60Mi
            requests:
              cpu: 15m
              memory: 30Mi
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: slack-usergroups
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /bin/sh
          - -c
          - while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} slack-usergroups ; sleep ${SLEEP_DURATION_SECS}; done
          resources:
            limits:
              cpu: 40m
              memory: 150Mi
            requests:
              cpu: 20m
              memory: 75Mi
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: jira-watcher
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /bin/sh
          - -c
          - while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} jira-watcher --io-dir /tmp/throughput/; sleep ${SLEEP_DURATION_SECS}; done
          resources:
            limits:
              cpu: 25m
              memory: 200Mi
            requests:
              cpu: 15m
              memory: 80Mi
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: github-scanner
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /bin/sh
          - -c
          - while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} github-scanner --thread-pool-size 1; sleep ${SLEEP_DURATION_SECS}; done
          env:
          - name: gitlab_pr_submitter_queue_url
            valueFrom:
              secretKeyRef:
                name: ${APP_INTERFACE_SQS_SECRET_NAME}
                key: gitlab_pr_submitter_queue_url
          resources:
            limits:
              cpu: 400m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        - name: aws-support-cases-sos
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /bin/sh
          - -c
          - while true; do qontract-reconcile --config /config/config.toml ${DRY_RUN} aws-support-cases-sos ; sleep ${SLEEP_DURATION_SECS}; done
          env:
          - name: gitlab_pr_submitter_queue_url
            valueFrom:
              secretKeyRef:
                name: ${APP_INTERFACE_SQS_SECRET_NAME}
                key: gitlab_pr_submitter_queue_url
          resources:
            limits:
              cpu: 50m
              memory: 200Mi
            requests:
              cpu: 25m
              memory: 100Mi
          volumeMounts:
          - name: qontract-reconcile-toml
            mountPath: /config
        volumes:
        - name: qontract-reconcile-toml
          secret:
            secretName: qontract-reconcile-toml
parameters:
- name: IMAGE
  value: quay.io/app-sre/qontract-reconcile
- name: IMAGE_TAG
  value: latest
- name: DRY_RUN
  value: --dry-run
- name: SLEEP_DURATION_SECS
  value: "300"
- name: APP_INTERFACE_SQS_SECRET_NAME
  value: app-interface-sqs
