query SaasFilesV2Full {
  apps_v1 {
    saasFiles {
      labels
      secretParameters {
        name
        secret {
          path
          format
        }
      }
      name
      pipelinesProvider {
        name
      }
      slack {
        channel
        username
      }
    }
  }
}
